#!/bin/bash

export home_folder=$(pwd)
export PROG_NAME=totinfo
export INDIR=${home_folder}/input.origin/n10train
export BIN=${home_folder}/src/reduced/n10train_cov/${PROG_NAME}.bin
export TIMEOUT=2
export OUTDIR=${home_folder}/testscript/n10train/result

echo '${BIN} ${OUTDIR} ${TIMEOUT} ${INDIR}'

